Repository kubernetes-sigs/bootkube, pull requests merged in 2018-05, with the labels that each got.

#970 bump to 1.10.2
  hack/multi-node/user-data.sample
  hack/quickstart/kubelet.master
  hack/quickstart/kubelet.worker
  hack/single-node/user-data.sample
  hack/tests/conformance-test.sh
  pkg/asset/images.go
Labels: cncf-cla: yes, size/S

#981 hack/quickstart: Use env file to keep track of master label/taint
  hack/quickstart/init-master.sh
  hack/quickstart/init-node.sh
  hack/quickstart/kubelet.master
  hack/quickstart/kubelet.service
Labels: cncf-cla: yes, size/M

#629 pkg/asset/internal: allow controller-manager to use cluster+host DNS
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/XS

#982 Update flannel vxlan port to 4789
  Documentation/network-requirements.md
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/XS
