Repository kubernetes-sigs/bootkube, pull requests merged in 2018-10, with the labels that each got.

#1000 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1009 checkpointer: ignore Affinity within podspec
  .travis.yml
  Makefile
  build/build-release.sh
  cmd/checkpoint/README.md
  hack/tests/conformance-gce.sh
  hack/tests/conformance-test.sh
  pkg/checkpoint/pod.go
  pkg/tlsutil/tlsutil.go
Labels: cncf-cla: yes, lgtm, size/S

#1010 images: bump checkpointer for affinity fix
  pkg/asset/images.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1011 start: add --require-pods flag
  cmd/bootkube/start.go
  pkg/bootkube/bootkube.go
  pkg/bootkube/status.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1013 start: fix CRD wait loop
  pkg/bootkube/create.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1018 fix typo Kubenetes -> Kubernetes
  Documentation/root-requirements.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1017 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
