Repository kubernetes-sigs/bootkube, pull requests merged in 2018-02, with the labels that each got.

#883 add terraform fmt validation
  .travis.yml
  Makefile
  hack/terraform-quickstart/main.tf
Labels: cncf-cla: yes, size/S

#885 Switch Deployments and DaemonSets to apps/v1
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/S

#886 assets: use MkdirAll to not error on existing dir
  pkg/asset/asset.go
Labels: cncf-cla: yes, size/S

#888 Remove PersistentVolumeLabel admission controller flag
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/XS

#887 Remove remaining etcd operator components
  cmd/bootkube/render.go
  e2e/etcdscale_test.go
  pkg/asset/asset.go
  pkg/asset/internal/templates.go
  pkg/recovery/etcd.go
Labels: cncf-cla: yes, size/L

#892 wait for the controlPlane to be restored
  e2e/deleteapi_test.go
Labels: cncf-cla: yes, size/S

#897 checkpointer: add 5m grace period flag.
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/XS

#898 pkg/bootkube: remove global variable
  pkg/bootkube/bootkube.go
  pkg/bootkube/create.go
  pkg/bootkube/status.go
Labels: cncf-cla: yes, size/M

#893 pkg/asset: Switch apiVersion to rbac.authorization.k8s.io/v1
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/S

#894 Update hyperkube image from v1.9.2 to v1.9.3
  Makefile
  hack/multi-node/user-data.sample
  hack/quickstart/kubelet.master
  hack/quickstart/kubelet.worker
  hack/single-node/user-data.sample
  hack/tests/conformance-test.sh
  pkg/asset/images.go
Labels: cncf-cla: yes, size/S

#900 e2e: better delete api wait condition.
  e2e/deleteapi_test.go
Labels: cncf-cla: yes, size/M

#904 add travis golang 1.10.x builder
  .travis.yml
Labels: cncf-cla: yes, size/XS

#907 Documentation: document new e2e command
  Documentation/development.md
Labels: cncf-cla: yes, size/XS

#854 e2e checkpointer test: remove node reboots
  e2e/checkpointer_test.go
Labels: cncf-cla: yes, size/M

#905 bootkube/pkg/recovery/recover fix hostNetwork
  pkg/recovery/recover.go
  pkg/recovery/recover_test.go
Labels: cncf-cla: yes, size/M

#908 recover: relax verification of etcd CAPath
  cmd/bootkube/recover.go
Labels: cncf-cla: yes, size/S
