Repository kubernetes-sigs/bootkube, pull requests merged in 2018-03, with the labels that each got.

#915 jenkins: add initial bootkube-e2e jobs
  hack/jenkins/README.md
  hack/jenkins/images/bootkube-e2e/Dockerfile
  hack/jenkins/jobs/bootkube_e2e.groovy
  hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
  hack/jenkins/scripts/e2e.sh
  hack/jenkins/scripts/tqs-down.sh
  hack/jenkins/scripts/tqs-up.sh
  hack/quickstart/init-master.sh
  hack/terraform-quickstart/main.tf
  hack/terraform-quickstart/variables.tf
Labels: cncf-cla: yes, size/L

#917 jenkins: update development readme with trigger information
  Documentation/development.md
  hack/jenkins/README.md
Labels: cncf-cla: yes, size/S

#923 error: SilenceErrors and tweak error output
  cmd/bootkube/main.go
Labels: cncf-cla: yes, size/XS

#918 jenkins: allow user to override repo_url
  hack/jenkins/jobs/bootkube_e2e.groovy
Labels: cncf-cla: yes, size/S

#924 Jenkins: Collect e2e logs & archive in public S3 bucket
  hack/jenkins/jobs/bootkube_e2e.groovy
  hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
  hack/jenkins/scripts/gather-logs.sh
  hack/jenkins/scripts/tqs-down.sh
  hack/jenkins/scripts/tqs-up.sh
Labels: cncf-cla: yes, size/M

#928 jenkins: bootkube-e2e: groovy interpolate repo name at job creation time
  hack/jenkins/jobs/bootkube_e2e.groovy
Labels: cncf-cla: yes, size/XS

#929 jenkins: prevent resource leak when log agg fails
  hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
Labels: cncf-cla: yes, size/XS

#927 pkg/asset: Migrate from Calico v2.6.6 to to 3.0.3
  pkg/asset/asset.go
  pkg/asset/images.go
  pkg/asset/internal/templates.go
  pkg/asset/k8s.go
Labels: cncf-cla: yes, size/L

#930 pkg/bootkube: create namespaces before other resources
  README.md
  pkg/bootkube/create.go
Labels: cncf-cla: yes, size/S

#933 pkg/bootkube: fix create always printing an error
  pkg/bootkube/create.go
Labels: cncf-cla: yes, size/XS

#931 docs: clarify 'latest' usage
  Documentation/disaster-recovery.md
Labels: cncf-cla: yes, size/XS

#938 pkg/checkpoint: support both CRI v1alpha1 and v1alpha2
  Gopkg.lock
  pkg/checkpoint/cri/README.md
  pkg/checkpoint/cri/v1alpha1/api.pb.go
  pkg/checkpoint/cri/v1alpha1/constants.go
  pkg/checkpoint/cri/v1alpha2/api.pb.go
  pkg/checkpoint/cri/v1alpha2/constants.go
  pkg/checkpoint/runtime_service.go
Labels: cncf-cla: yes, size/XXL

#940 pkg/asset: update checkpointer to include CRI v1alpha2 support
  pkg/asset/images.go
Labels: cncf-cla: yes, size/XS

#939 add strict mode for start
  cmd/bootkube/start.go
  hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
  hack/quickstart/init-master.sh
  hack/terraform-quickstart/start-cluster.sh
  pkg/bootkube/bootkube.go
  pkg/bootkube/create.go
Labels: cncf-cla: yes, size/M

#942 pkg/assets: calico 3.0 rbac typo
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/XS

#943 Documentation/root-requirements: API server no longer needs root
  Documentation/root-requirements.md
Labels: cncf-cla: yes, size/XS

#952 OWNERS: update owners
  OWNERS
Labels: cncf-cla: yes, size/XS
