Repository kubernetes-sigs/bootkube, pull requests merged in 2018-04, with the labels that each got.

#947 Makefile: Drop GO15VENDOREXPERIMENT
  Makefile
Labels: cncf-cla: yes, size/XS

#951 build/git-version: Only call 'git' once
  build/git-version.sh
Labels: cncf-cla: yes, size/S

#953 add hyperkube release scripts
  hack/jenkins/README.md
  hack/jenkins/images/hyperkube-builder/Dockerfile
  hack/jenkins/jobs/hyperkube_release.groovy
  hack/jenkins/pipelines/hyperkube-release/Jenkinsfile
Labels: cncf-cla: yes, size/M

#949 Makefile: Respect GOBIN
  Documentation/development.md
  Makefile
Labels: cncf-cla: yes, size/S

#956 Makefile: Actually use 'go install ...' for the install target
  Makefile
Labels: cncf-cla: yes, size/XS

#958 README: Update the Slack link
  README.md
Labels: cncf-cla: yes, size/XS

#957 Replace Jenkins `sh` with a `bash` step that sets `set -euo pipefail`
  hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
  hack/jenkins/pipelines/hyperkube-release/Jenkinsfile
Labels: cncf-cla: yes, size/M

#961 fix IMAGE_TAG in hyperkube release
  hack/jenkins/pipelines/hyperkube-release/Jenkinsfile
Labels: cncf-cla: yes, size/XS

#954 bump to 1.10.0
  hack/jenkins/scripts/tqs-down.sh
  hack/jenkins/scripts/tqs-up.sh
  hack/multi-node/user-data.sample
  hack/quickstart/kubelet.master
  hack/quickstart/kubelet.worker
  hack/single-node/user-data.sample
  hack/terraform-quickstart/main.tf
  hack/terraform-quickstart/variables.tf
  hack/tests/conformance-test.sh
  pkg/asset/images.go
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/M

#962 use k8s.gcr.io mirror
  hack/multi-node/user-data.sample
  hack/quickstart/kubelet.master
  hack/quickstart/kubelet.worker
  hack/single-node/user-data.sample
  pkg/asset/images.go
Labels: cncf-cla: yes, size/S

#963 Remove deprecated admission plugin flag
  pkg/asset/internal/templates.go
Labels: cncf-cla: yes, size/XS

#964 bump to 1.10.1
  hack/multi-node/user-data.sample
  hack/quickstart/kubelet.master
  hack/quickstart/kubelet.worker
  hack/single-node/user-data.sample
  hack/tests/conformance-test.sh
  pkg/asset/images.go
Labels: cncf-cla: yes, size/S

#965 Update kube-dns from v1.14.8 to v1.14.9
  pkg/asset/images.go
Labels: cncf-cla: yes, size/XS

#967 remove jenkins jobs that were migrated elsewhere
  hack/jenkins/images/hyperkube-builder/Dockerfile
  hack/jenkins/jobs/hyperkube_release.groovy
  hack/jenkins/pipelines/hyperkube-release/Jenkinsfile
Labels: cncf-cla: yes, size/M

#968 hack/jenkins: use quay image for bootkube-e2e test
  hack/jenkins/pipelines/bootkube-e2e/Jenkinsfile
Labels: cncf-cla: yes, size/XS
