Repository kubernetes-sigs/bootkube, pull requests merged in 2018-11, with the labels that each got.

#1019 Typo in the returned message in runtime_service.go
  pkg/checkpoint/runtime_service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1021 Delete repeated 'the'
  pkg/recovery/recover.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1024 Fix typo: resouces -> resource
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1026 Fix typos: genereted->generated, verison->version
  cmd/bootkube/start.go
  pkg/bootkube/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1023 update coredns
  pkg/asset/images.go
  pkg/asset/internal/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1028 Fix typos: commma -> comma, requried -> required, etc
  cmd/bootkube/render.go
  cmd/checkpoint/README.md
  e2e/internal/e2eutil/testworkload/nginx_workload.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1027 pkg/checkpoint: Try kubelet secureClient, fallback to read-only
  pkg/checkpoint/checkpoint.go
  pkg/checkpoint/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1030 start: wait until pods ready
  cmd/bootkube/start.go
  pkg/bootkube/status.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1016 Make e2e test commands copy-pastable
  hack/multi-node/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1031 Update pod-checkpointer image to try secureClient first
  pkg/asset/images.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
