Repository kubernetes-sigs/bootkube, pull requests merged in 2018-08, with the labels that each got.

#998 Bump v1.11.2
  Gopkg.lock
  Gopkg.toml
  Makefile
  hack/jenkins/scripts/conformance.sh
  hack/multi-node/user-data.sample
  hack/quickstart/kubelet.service
  hack/single-node/user-data.sample
  hack/tests/conformance-test.sh
  pkg/asset/images.go
  pkg/checkpoint/internal/README.md
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
Labels: cncf-cla: yes, size/XXL

#946 DCO: Remove unused file
  DCO
Labels: cncf-cla: yes, size/M

#948 Makefile: Drop hard-coded Bash and simplify gofmt
  Makefile
Labels: cncf-cla: yes, size/S

#950 Makefile: Remove clean prerequisites from build targets
  .travis.yml
  Documentation/development.md
  Makefile
Labels: cncf-cla: yes, size/S
