Repository kubernetes-sigs/bootkube, pull requests merged in 2019-11, with the labels that each got.

#1055 Update SECURITY_CONTACTS.
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1050 Improve upgrading docs
  Documentation/upgrading.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1056 Update kubernetes to 1.16
  Makefile
  go.mod
  go.sum
  hack/multi-node/bootkube-up
  hack/multi-node/user-data.sample
  hack/single-node/user-data.sample
  pkg/asset/images.go
  pkg/asset/internal/templates.go
  pkg/bootkube/create.go
  pkg/bootkube/status.go
  pkg/checkpoint/config_map.go
  pkg/checkpoint/internal/README.md
  pkg/checkpoint/kubelet.go
  pkg/checkpoint/secret.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1048 updates cri v1alpha2
  pkg/checkpoint/cri/README.md
  pkg/checkpoint/cri/v1alpha2/api.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1060 updates flannel
  pkg/asset/images.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1061 update coredns and config for 1.6.2
  pkg/asset/images.go
  pkg/asset/internal/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1062 fixes help text to show experimental-calico
  cmd/bootkube/render.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1065 Fix broken link of api versioning documentation
  Documentation/alpha-features.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1064 feat: enable aggregation layer
  pkg/asset/asset.go
  pkg/asset/internal/templates.go
  pkg/asset/k8s.go
  pkg/asset/tls.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1067 fix: add aggregation layer flags to API server DaemonSet
  pkg/asset/internal/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1068 fix: remove node selector from static manifests
  pkg/checkpoint/manifest.go
  pkg/checkpoint/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/M
